### ISSUE TITLE
Create security response team

### ISSUE THREAD

**Issue by dstebila** [open-quantum-safe/tsc#112]
From the November 5 TSC meeting, the following people volunteered to be part of a security response team for OQS:

- @baentsch 
- @bhess 
- @brian-jarvis-aws 
- @dstebila 
- @praveksharma 
- @SWilson4 

@ryjones, what do we need to do in Github for this?  Is there a security team that should be created?  And given relevant status?

**Comment by ryjones** [comment]
@dstebila the TSC has this role now. I filed a PR to create the team.

**Comment by dstebila** [comment]
> @dstebila the TSC has this role now. I filed a PR to create the team. When merged I'll set the proper role.

Thanks very much!
