### ISSUE TITLE
Obtain funding for ARM CI GH runners

### ISSUE THREAD

**Issue by baentsch** [open-quantum-safe/tsc#25]
As per https://github.com/open-quantum-safe/liboqs/issues/1789#issuecomment-2105730555

**Comment by dstebila** [comment]
@hartm What would the process be for getting approval to spend money Github ARM runners?

**Comment by hartm** [comment]
We just had a staff discussion about this.  @ryjones has created a new thread, which he plans to bring to the TAC next week:  https://github.com/PQCA/TAC/issues/20

The basic idea is that we first need an estimate of the budget needed.  Ry is the expert here and can help figure things out.  Then we will discuss at the TAC meeting and get approval at the board meeting.  Hopefully we can get this all done next week.

From our rough estimates, this should be very feasible and we should definitely have the budget.

**Comment by ryjones** [comment]
done
