### ISSUE TITLE
Create project for tracking issues across repositories

### ISSUE THREAD

**Issue by planetf1** [open-quantum-safe/tsc#29]
As per https://github.com/orgs/open-quantum-safe/discussions/1791 I suggest we create a Github project board at the organization level for tracking issues across repositories.

The 'Bug Tracker' template is probably a good start as it's mostly simple priority/category views rather than getting into iteration/feature planning. 

All the templates are totally customizable.

I do not have access to create a board (and unfortunately a board can't just be 'moved'), but if one were to be created I'd be happy to work with @baentsch and others on trying to get something customized that helps us track issues across the project.

However I will need to be given access to help out in that way :-) Probably 'write' access is sufficient and can be applied purely to the project -> see https://docs.github.com/en/issues/planning-and-tracking-with-projects/managing-your-project/managing-access-to-your-projects . May need to check how this works alongside the LF tooling for permissions - using an existing group & inherited repo permissions may be preferable.

**Comment by baentsch** [comment]
I don't have the permissions to do this anymore. @ryjones Can you please help @planetf1 here?

**Comment by planetf1** [comment]
I see we now have a project at https://github.com/orgs/open-quantum-safe/projects/7 so closing

We can review the board in future dev/tsc meetings & customize as needed
