### ISSUE TITLE
Request access to oqs

### ISSUE THREAD

**Issue by planetf1** [open-quantum-safe/tsc#33]
I'd like to request access to OQS at an appropriate level to be able to:
 - assign issues to myself
 - review content discussed on dev team calls such as vulnerabilities
 
 cc: @dstebila @ryjones

**Comment by dstebila** [comment]
I approve.

**Comment by ryjones** [comment]
@dstebila which group?

**Comment by dstebila** [comment]
I guess the Triage role is the Github access level that matches this request?

**Comment by ryjones** [comment]
@dstebila see the PR
