### ISSUE TITLE
Schedule next TSC meeting

### ISSUE THREAD

**Issue by dstebila** [open-quantum-safe/tsc#9]
Agenda items: see https://github.com/open-quantum-safe/tsc/blob/main/meetings/2024-04-xx/agenda.md

**Comment by ashman-p** [comment]
Douglas, When is the next meeting?
Thanks.

**Comment by baentsch** [comment]
fwiw, I'll be unavailable Apr 12-22.

**Comment by dstebila** [comment]
> Douglas, When is the next meeting? Thanks.

There's a poll to schedule the meeting here: https://doodle.com/meeting/participate/id/ep9r51Va

**Comment by dstebila** [comment]
> fwiw, I'll be unavailable Apr 12-22.

Noted.

**Comment by dstebila** [comment]
The next TSC meeting is April 10, 2024, 5pm Central European / 11am US Eastern / 8am US Pacific. See https://github.com/open-quantum-safe/tsc/blob/main/meetings/2024-04-10/agenda.md
